/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_dynamodb_all_tables_region": "sa-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "patients-dev",
            "region": "sa-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "mctestapi",
            "endpoint": "https://bl5fp3mond.execute-api.sa-east-1.amazonaws.com/dev",
            "region": "sa-east-1"
        }
    ]
};


export default awsmobile;
